name: t20-fri-mvp
channels:
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.2
  - jupyter=1.0.0
  - matplotlib=3.2.1
  - notebook=6.0.3
  - numpy=1.18.5
  - pillow=7.1.2
  - pip=20.1.1
  - python=3.7.6
  - requests=2.23.0
  - scikit-learn=0.21.3
  - scipy=1.4.1
  - pip:
    - brotli==1.0.7
    - dash==1.12.0
    - dash-core-components==1.10.0
    - dash-html-components==1.0.3
    - dash-renderer==1.4.1
    - dash-table==4.7.0
    - flask-compress==1.5.0
    - future==0.18.2
    - jupyter-dash==0.2.1.post1
    - plotly==4.8.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - retrying==1.3.3

